name: build and deploy

on:
  push:
    branches: ['master']

env:
  NODE_VERSION: '18'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: create ssh key
        run: |
          echo "${{ secrets.WS_SSH }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem

      - name: build
        run: |
          npm install
          npm run build

      - name: deploy
        run: |
          scp -i ~/private-key.pem -o StrictHostKeyChecking=no -rpv -P 22 ./build/* ec2-user@15.164.233.95:/app/wichan-nginx
